name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image, update Helm chart, and publish to gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      actions: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            joseph888/apinombres:${{ github.sha }}

      - name: Install yq and Helm
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Checkout Helm chart repo
        uses: actions/checkout@v4
        with:
          repository: joseph8884/ManifestsApiNombres 
          ref: chart 
          path: ManifestsApiNombres
          token: ${{ secrets.JOSE_TOK }}

      - name: Update Helm chart image tag and version
        run: |
          cd ManifestsApiNombres/my-helm-chart2
          # Incrementar versión automáticamente (ej: 0.1.0 → 0.1.1)
          CURRENT_VERSION=$(yq eval '.version' Chart.yaml)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          yq eval ".version = \"$NEW_VERSION\"" -i Chart.yaml

          # Actualizar tag de la imagen
          yq eval ".image.tag = \"${{ github.sha }}\"" -i values.yaml

      - name: Package Helm chart
        run: |
          cd ManifestsApiNombres/my-helm-chart2
          helm package . --destination ./charts

      - name: Prepare gh-pages branch
        run: |
          cd ManifestsApiNombres
          git checkout --orphan gh-pages
          git rm -rf .
          mkdir -p charts/$NEW_VERSION
          cp my-helm-chart2/charts/*.tgz charts/$NEW_VERSION/
          helm repo index charts --url https://joseph8884.github.io/ManifestsApiNombres/charts

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Publish chart version $NEW_VERSION"
          git push origin gh-pages --force

      - name: Push changes to chart repo
        run: |
          cd ManifestsApiNombres
          git add .
          git commit -m "Update chart to version $NEW_VERSION"
          git push