name: CI / CD

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image and update Helm chart
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Usamos el SHA del commit como tag
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            joseph888/apinombres:${{ github.sha }}

      # Instalar yq para manipular YAML
      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      # Clonar el repositorio del chart Helm (ajusta la URL)
      - name: Checkout Helm chart repo
        uses: actions/checkout@v4
        with:
          repository: joseph8884/ManifestsApiNombres
          path: ManifestsApiNombres
          token: ${{ secrets.GIT_TOKEN }}  # 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

      # Actualizar el tag en values.yaml del chart
      - name: Update Helm chart image tag
        run: |
          cd my-helm-chart
          yq eval ".image.tag = \"${{ github.sha }}\"" -i values.yaml  # Ajusta la ruta

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update image tag to ${{ github.sha }}"
          git push